import type { NextPage } from "next";
import Head from "next/head";
import FixedBottomNavigation from "../components/BottomNav";
import Content from "../components/Content";
import Navbar from "../components/Nav";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>TokopediApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </Head>

      <main className={styles.main}>
        <Navbar />
        <Content />

        <FixedBottomNavigation />
      </main>
    </div>
  );
};

export default Home;
